### ISSUE TITLE
Firebase config file shouldn't be in the repository

### ISSUE THREAD

**Issue by juandelgado** [selfcontained/slapp-firebase-example#1]
Hello!

I'm wondering about this on your README:

> Also expected is a Firebase Service account key file located in the root of the project, named firebase.json.

Since BeepBoop actually builds the image from `Dockerfile`, then `firebase.json` *must* be in the repository, which is very bad practice since it contains sensitive information like the private key.

Reading up on [Firebase's docs](https://firebase.google.com/docs/admin/setup), I _think_ that the information contained in `firebase.json` could be passed via ENV vars, but I'm counting 10 different values in it, which would make booting up the app in BeepBoop a very tedious and error prone process.

Maybe I could try to pass the whole of the JSON file as a string blob in a single ENV, but who knows if that's going to work with all the weird characters.

So right now I'm torn between an unacceptable method (config file in the repo) or a very tedious and error prone one (passing 10 different ENV vars).

But I might be missing something?

Thanks!

Juan

**Comment by selfcontained** [comment]
Totally agree.  For the simplicity of this sample repo I put `/firebase.json` in the `.gitignore` to keep people from inadvertently checking that in without thinking, but didn't want to make an opinionated decision about how you'd pass that in or get that file there since it's meant to be a platform agnostic example of how to use slapp w/ firebase.

On a platform like BeepBoop (or any that supports env vars for config) I've passed in the contents of the `firebase.json` file as a base64 encoded value through an environment variable, and then on startup, written it out to disk (the only way I could see getting the `firebase` module to use a service account was via a filename, and not the contents or values directly).

**Comment by juandelgado** [comment]
> I've passed in the contents of the firebase.json file as a base64 encoded value through an environment variable, and then on startup, written it out to disk

That's actually a good shout and one decent way around it. 

In the mean time, I've been digging a bit more and found that in reality you only need 3 of the values of the config JSON:
- projectId
- clientEmail
- privateKey

The [docs](https://firebase.google.com/docs/admin/setup) are right (note that there's been an update, 3.6.0 has been published only 2 days ago) and it means that you would only need to pass those 3 vars to BeepBoop via `bot.yml`.

But all in all I think the [blog post](https://blog.beepboophq.com/creating-a-slack-app-with-slapp-firebase-83e4ad139006#.nkl2nmcl7) and the README of this repo could do with an update making more explicit how to get the Firebase config setup in a simple and secure way.

Cheers.

**Comment by selfcontained** [comment]
Ah cool, thanks for the info, this new section in the docs is probably the way to go, like you said:

![image](https://cloud.githubusercontent.com/assets/367275/20196430/e4abeb74-a757-11e6-9f9d-17cb1b2f7a87.png)

**Comment by selfcontained** [comment]
I've updated the demo to use the `firebase-admin` module which allows us to pass in a credentials object instead of using the file system.  Since the `privateKey` has significant line breaks it requires some type of encoding.  I have it setup now so it's expecting an env var named `FIREBASE_SERVICE_ACCOUNT_BASE64` that is a base64 encoded string of the entire json key file you download from Firebase.  I thought of just doing that for the `privateKey` and having `projectId` and `clientEmail` as their own env vars, but since some encoding was required for one, I thought it'd be simpler to just expect the entire credential object to be encoded.  This may offer some future-proofing as well if additional props are used in the future.   The README has been updated to reflect this as well.

**Comment by cross19xx** [comment]
> > I've passed in the contents of the firebase.json file as a base64 encoded value through an environment variable, and then on startup, written it out to disk
> 
> That's actually a good shout and one decent way around it.
> 
> In the mean time, I've been digging a bit more and found that in reality you only need 3 of the values of the config JSON:
> 
> * projectId
> * clientEmail
> * privateKey
> 
> The [docs](https://firebase.google.com/docs/admin/setup) are right (note that there's been an update, 3.6.0 has been published only 2 days ago) and it means that you would only need to pass those 3 vars to BeepBoop via `bot.yml`.
> 
> But all in all I think the [blog post](https://blog.beepboophq.com/creating-a-slack-app-with-slapp-firebase-83e4ad139006#.nkl2nmcl7) and the README of this repo could do with an update making more explicit how to get the Firebase config setup in a simple and secure way.
> 
> Cheers.

Found this through the Intellisense of VSCode.
